-- MySQL Script generated by MySQL Workbench
-- Sun Mar 10 17:47:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

select * from gomesgalvaofacilities.conjunto;
select * from gomesgalvaofacilities.secao;
select * from gomesgalvaofacilities.slide;


delete from gomesgalvaofacilities.slide where id>0;
delete from gomesgalvaofacilities.conjunto where id>0;
delete from gomesgalvaofacilities.secao where id>0;



SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GomesGalvaoFacilities
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GomesGalvaoFacilities
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GomesGalvaoFacilities` DEFAULT CHARACTER SET utf8 ;
USE `GomesGalvaoFacilities` ;

-- -----------------------------------------------------
-- Table `GomesGalvaoFacilities`.`secao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GomesGalvaoFacilities`.`secao` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(50) NULL,
  `img` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GomesGalvaoFacilities`.`conjunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GomesGalvaoFacilities`.`conjunto` (
  `id` INT NOT NULL,
  `texto` VARCHAR(311) NULL,
  `img` VARCHAR(50) NULL,
  `idsecao` INT NOT NULL,
  PRIMARY KEY (`id`, `idsecao`),
  INDEX `fk_Conjunto_Secao_idx` (`idsecao` ASC),
  CONSTRAINT `fk_Conjunto_Secao`
    FOREIGN KEY (`idsecao`)
    REFERENCES `GomesGalvaoFacilities`.`secao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GomesGalvaoFacilities`.`slide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GomesGalvaoFacilities`.`slide` (
  `id` INT NOT NULL,
  `img` VARCHAR(50) NULL,
  `titulo` VARCHAR(50) NULL,
  `minitexto` VARCHAR(63) NULL,
  `texto` VARCHAR(235) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
